### ISSUE TITLE
Unable to install from plugin marketplace

### ISSUE THREAD

**Issue by davidak** [DiamondYuan/logseq-eink-theme#4]
Error in terminal:

```
05:55:53.933 › [Marketplace] === Installing: DiamondYuan/logseq-eink-theme ===
05:55:54.263 › [Marketplace] Error: Github API Failed(404) {"message":"Not Found","documentation_url":"https://docs.github.com/rest/releases/releases#get-the-latest-release"}
    at /nix/store/0wrz0hvh8q7kya0hr94jqr54xawamfy6-logseq-0.10.5/share/logseq/resources/app/electron.js:14194:25
    at Function.$G__107959__1$$ [as $cljs$core$IFn$_invoke$arity$1$] (/nix/store/0wrz0hvh8q7kya0hr94jqr54xawamfy6-logseq-0.10.5/share/logseq/resources/app/electron.js:4104:175)
    at /nix/store/0wrz0hvh8q7kya0hr94jqr54xawamfy6-logseq-0.10.5/share/logseq/resources/app/electron.js:13064:80
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
05:55:54.264 › [Marketplace] Error: [:release-channel-issue "Github API Failed(404) {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/releases/releases#get-the-latest-release\"}"]
    at /nix/store/0wrz0hvh8q7kya0hr94jqr54xawamfy6-logseq-0.10.5/share/logseq/resources/app/electron.js:14228:11
    at /nix/store/0wrz0hvh8q7kya0hr94jqr54xawamfy6-logseq-0.10.5/share/logseq/resources/app/electron.js:13090:152
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Using Logseq 0.10.5

**Comment by fpigeonjr** [comment]
confirmed. also tried to install from marketplace and got the same result.

**Comment by yeahwong** [comment]
Me too
